### ISSUE TITLE
Inkscape vanished

### ISSUE THREAD

**Issue by agoltz** [caskformula/homebrew-caskformula#11]
The brew apparently finished, but Inkscape is nowhere to be seen.

**Comment by tghs** [comment]
Currently the formula doesn't build a regular `.app` bundle that goes into your `/Applications` folder. You have to manually invoke it from Terminal by running the `inkscape` command by hand.

I hope to make this formula produce a `.app` bundle, and this is tracked in issue #2.

**Comment by agoltz** [comment]
Thank you very much for the explanation!

Andrew
