### ISSUE TITLE
Configure fails: ld: _libintl_textdomain symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by kbaryshnikov** [caskformula/homebrew-caskformula#13]
Sierra 10.12.5 (16F73)
16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

Homebrew 1.2.2
Homebrew/homebrew-core (git revision e82aa; last commit 2017-06-05)

```
==> Downloading from https://launchpadlibrarian.net/306309537/inkscape-0.92.1.tar.bz2
######################################################################## 100.0%
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/inkscape/0.92.1 --disable-silent-rules --disable-strict-build --enable-lcms --without-gnome-vfs
==> make
Last 15 lines from /Users/fixxxer/Library/Logs/Homebrew/inkscape/03.make:
      _main in inkview.o
  "_libintl_textdomain", referenced from:
      _main in main.o
  "_libintl_textdomain", referenced from:
      _main in inkview.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: symbol(s) not found for architecture x86_64
make[3]: *** [inkscape] Error 1
make[3]: *** Waiting for unfinished jobs....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [inkview] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by tghs** [comment]
I've switched from the autotools build to the cmake build. Can you please confirm whether this still happens?

I'll close the issue, but please reopen it if this is still a problem.

**Comment by kbaryshnikov** [comment]
```
==> mkdir build
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/inkscape/0.92.2_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=
==> make                                                                                                                                                                                         Last 15 lines from /Users/fixxxer/Library/Logs/Homebrew/inkscape/03.make:
      ...
  "_iconv_open", referenced from:
      _U_Utf32leToUtf16le in libuemf_LIB.a(uemf_utf.c.o)
      _U_Utf16leToUtf32le in libuemf_LIB.a(uemf_utf.c.o)
      _U_Latin1ToUtf32le in libuemf_LIB.a(uemf_utf.c.o)
      _U_Utf8ToUtf32le in libuemf_LIB.a(uemf_utf.c.o)
      _U_Utf32leToUtf8 in libuemf_LIB.a(uemf_utf.c.o)
      _U_Utf8ToUtf16le in libuemf_LIB.a(uemf_utf.c.o)
      _U_Utf16leToUtf8 in libuemf_LIB.a(uemf_utf.c.o)
      ...
ld: symbol(s) not found for architecture x86_64
```

**Comment by dleclere** [comment]
I'm getting a similar error:
==> mkdir build
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
Last 15 lines from /Users/dleclere/Library/Logs/Homebrew/inkscape/03.make:
      Inkscape::IO::GzipInputStream::fetchMore() in gzipstream.cpp.o
      Inkjar::JarFile::get_compressed_file(unsigned int, unsigned int&, unsigned int, unsigned short) in inkjar.cpp.o
  "_inflateEnd", referenced from:
      Inkscape::IO::GzipInputStream::close() in gzipstream.cpp.o
      Inkjar::JarFile::close() in inkjar.cpp.o
  "_inflateInit2_", referenced from:
      Inkscape::IO::GzipInputStream::load() in gzipstream.cpp.o
      Inkjar::JarFile::init_inflation() in inkjar.cpp.o
  "_inflateReset", referenced from:
      Inkjar::JarFile::get_compressed_file(unsigned int, unsigned int&, unsigned int, unsigned short) in inkjar.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libinkscape_base.dylib] Error 1
make[1]: *** [src/CMakeFiles/inkscape_base.dir/all] Error 2
make: *** [all] Error 2

**Comment by twogee** [comment]
@kbaryshnikov build picks up bad libiconv, @dleclere build picks up bad libz
does e.g. `locate libiconv.dylib` provide any clues? See also #26

**Comment by dleclere** [comment]
locate libiconv.dylib
/Applications/GIMP.app/Contents/Resources/lib/libiconv.dylib
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/lib/libiconv.dylib
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/lib/libiconv.dylib
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libiconv.dylib
/opt/local/lib/libiconv.dylib
/usr/lib/libiconv.dylib
/usr/local/MacGPG2/lib/libiconv.dylib

**Comment by twogee** [comment]
Sorry for confusing the matter with the wrong example. In your case, the culprit may be indicated by `locate libz.dylib`. Also, `brew doctor` may provide some clues. From the output above, `/opt/local/lib` looks suspicious...
