### ISSUE TITLE
problem downloading inkscape 

### ISSUE THREAD

**Issue by moramaldonado** [caskformula/homebrew-caskformula#15]
Hi, 

I have been trying to download inkscape with the brew install caskformula/caskformula/inkscape command and I get the following error: 

./configure: line 5798: syntax error near unexpected token `2.2'

Do you know from where this error comes?

Thanks in advance.

**Comment by wyoung** [comment]
It comes from having one or more versions of GNU libtool installed via Homebrew, which masks the platform version provided by Apple, which is more likely to work than the Homebrew versions. Say

    brew uninstall --force libtool

Then retry the installation.

**Comment by tghs** [comment]
This should no longer be an issue. Since moving to cmake-based builds, `./configure` is no longer called.
