### ISSUE TITLE
not exist libpng-1.6.18.tar.xz

### ISSUE THREAD

**Issue by tiehan** [caskformula/homebrew-caskformula#16]
Now libpng-1.6.18.tar.xz has changed to libpng-1.6.30

So can't download libpng

==> Installing dependencies for pdf2htmlex: libpng, freetype, fontconfig, pixman, gettext, libffi, glib, cairo, gobject-introspection, jpeg, libtiff, little-cms2, openjpeg, p
==> Installing pdf2htmlex dependency: libpng
==> Downloading ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.18.tar.xz

curl: (78) RETR response: 550
Error: Failed to download resource "libpng"
Download failed: ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.18.tar.xz

**Comment by tghs** [comment]
What command did you run to get that? `brew install pdf2htmlex`?

**Comment by tghs** [comment]
Closing. Either an [upstream](https://github.com/Homebrew/homebrew-core) issue or need more information.
