### ISSUE TITLE
Installing inkscape failed

### ISSUE THREAD

**Issue by Anredamati** [caskformula/homebrew-caskformula#20]
When I try to install inkscape I get the following:

MacBook-Pro-van-Anita:~ Mijnmac$ brew install caskformula/caskformula/inkscape
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing inkscape from caskformula/caskformula
Error: The following formula:
  inkscape
cannot be installed as a binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

MacBook-Pro-van-Anita:~ Mijnmac$

**Comment by tghs** [comment]
If you run `xcode-select --install` then you'll get the compiler and development tools installed. After you do this, try installing inkscape in the same way again.
