### ISSUE TITLE
Inkscape fails to install on Yosemite

### ISSUE THREAD

**Issue by Sk1nk** [caskformula/homebrew-caskformula#22]
$ brew install caskformula/caskformula/inkscape
==> Installing inkscape from caskformula/caskformula
==> Downloading https://launchpad.net/inkscape/0.92.x/0.92.2/+download/inkscape-
Already downloaded: /Users/max/Library/Caches/Homebrew/inkscape-0.92.2.tar.bz2
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/inkscape/0.92.2 --disable-silent-rule
==> make
Last 15 lines from /Users/max/Library/Logs/Homebrew/inkscape/03.make:
inline Object Object::dictLookup(const char *key, int recursion)
                                                      ^
extension/internal/pdfinput/pdf-parser.cpp:774:8: error: 'free' is a private member of 'Object'
  obj2.free();
       ^
/usr/local/Cellar/poppler/0.59.0_1/include/poppler/Object.h:291:8: note: declared private here
  void free();
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [extension/internal/pdfinput/pdf-parser.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by Averethel** [comment]
Have the same on sierra

**Comment by dschneiderch** [comment]
looks similar to #21. I think you need to either downgrade poppler and/or install `harfbuzz`

**Comment by tghs** [comment]
Yep, same issue as #21. I'm closing the duplicates and keeping #21 open as most of the discussion about this is there.
