### ISSUE TITLE
Inkscape Fails to install Error 2

### ISSUE THREAD

**Issue by malcinator** [caskformula/homebrew-caskformula#23]
Tried following along with the other issues and found an issue of my own.
macOS 10.12.6
Output from terminal......
$ brew install caskformula/caskformula/inkscape
Updating Homebrew...
==> Installing inkscape from caskformula/caskformula
==> Downloading https://launchpad.net/inkscape/0.92.x/0.92.2/+download/inkscape-0.92.2.tar.bz2
Already downloaded: /Users/malc/Library/Caches/Homebrew/inkscape-0.92.2.tar.bz2
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/inkscape/0.92.2 --disable-silent-rules --disable-strict-build --enable-lcms --without-gnome-vfs
==> make
Last 15 lines from /Users/malc/Library/Logs/Homebrew/inkscape/03.make:
        ~~~~~~~~~~~~~~~~~ ^~~~
/usr/local/include/poppler/Page.h:199:3: note: 'getContents' declared here
  Object getContents() { return contents.fetch(xref); }
  ^
extension/internal/pdfinput/pdf-input.cpp:850:13: error: 'free' is a private member of 'Object'
        obj.free();
            ^
/usr/local/Cellar/poppler/0.59.0_1/include/poppler/Object.h:291:8: note: declared private here
  void free();
       ^
2 errors generated.
make[3]: *** [extension/internal/pdfinput/pdf-input.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by Andrew681** [comment]
On an earlier thread, I found a suggestion to replace poppler v0.59 with v0.57, and then try reinstalling inkscape, but I haven't yet found out how to revert to that earlier version (which I don't have)

**Comment by keksipurkki** [comment]
Following @Andrew681's suggestion, I managed to workaround the issue. Here are the steps:

```sh
brew edit caskformula/caskformula/inkscape # Change poppler to poppler@0.57 
brew uninstall poppler # Make sure poppler is removed

# Poppler 0.57 formula has been removed from Homebrew; bring it back
git -C "$(brew --repo homebrew/core)" show 14cb0b8c0^:Formula/poppler@0.57.rb > poppler@0.57.rb
brew install --build-from-source poppler@0.57.rb && rm poppler@0.57.rb

brew install caskformula/caskformula/inkscape

```

**Comment by tghs** [comment]
This is the same issue as #21. I'm closing the duplicates and keeping #21 open to track this issue.
