### ISSUE TITLE
I can not compile Inkscape with MacOSX ElCapitan

### ISSUE THREAD

**Issue by WAKAMAZU** [caskformula/homebrew-caskformula#25]
make
Last 15 lines from /Users/WAKAMATSU/Library/Logs/Homebrew/inkscape/03.make:
inline Object Object::dictLookup(const char *key, int recursion)
                                                      ^
extension/internal/pdfinput/pdf-parser.cpp:774:8: error: 'free' is a private member of 'Object'
  obj2.free();
       ^
/usr/local/Cellar/poppler/0.59.0_1/include/poppler/Object.h:291:8: note: declared private here
  void free();
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [extension/internal/pdfinput/pdf-parser.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

WAKAMATSU from Japan [2017/09/08 20:30:13]

**Comment by WAKAMAZU** [comment]
As [dschneiderch]reported in this issue, I change my popler 0.57.0_1.
[ brew switch poppler 0.57.0_1 ] , this make me promising approach installing Inkscape 0.92.2 on my
OSX 10.11 ElCapitan .
Now I can use Inkscape in Japanese, again.
(Otherwise, Inkscape.app can not write directory in a document with Japanese UIM.)
I am delighted to report that . Yours, WAKAMATSU
P.S
dschneiderch, 
Thank a lot for your report.

**Comment by kenyee** [comment]
Bit me too...had to run "brew switch poppler 0.57.0_1" and then reinstall inkscape.

**Comment by tghs** [comment]
This is the same issue as #21. I'm closing the duplicates and keeping #21 open to track this issue.
