### ISSUE TITLE
Failure during reinstalling (following steps on https://inkscape.org/en/download/mac-os/)

### ISSUE THREAD

**Issue by bytebunny** [caskformula/homebrew-caskformula#49]
/tmp/inkscape-20180420-91785-vcm90p/inkscape-0.92.2/src/extension/internal/pdfinput/pdf-parser.cpp:2575:18: error: cannot initialize a parameter of type 'GooString *' with an rvalue of type 'const GooString *'
      doShowText(obj.getString());
                 ^~~~~~~~~~~~~~~
/tmp/inkscape-20180420-91785-vcm90p/inkscape-0.92.2/src/extension/internal/pdfinput/pdf-parser.h:290:30: note: passing argument to parameter 's' here
  void doShowText(GooString *s);
                             ^
/tmp/inkscape-20180420-91785-vcm90p/inkscape-0.92.2/src/extension/internal/pdfinput/pdf-parser.cpp:2735:9: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
  char *name = args[0].getName();
        ^      ~~~~~~~~~~~~~~~~~
5 errors generated.
make[2]: *** [src/CMakeFiles/inkscape_base.dir/extension/internal/pdfinput/pdf-parser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/inkscape_base.dir/all] Error 2
make: *** [all] Error 2

**Comment by airhadoken** [comment]
I had the same problem installing today as well.  It looks like the lib dependency `poppler` was updated on 2018-04-17 and is the source of all the compilation failures: some return values were changed to pointers-to-`const`.

To work around this until the build can be updated, downgrade poppler to the previous version (0.64 -> 0.63_1) using these brew commands:

```
$ brew unlink poppler
$ brew install https://raw.github.com/homebrew/homebrew-core/9d6847c5cbca3d0b8dad08a6e6bccd68d99291f9/Formula/poppler.rb
$ brew install inkscape
```

**Comment by airhadoken** [comment]
Unfortunately, that only got me as far as #41 / #42 / #43.  There's still a problem with `glibmm` and `libc++` that will probably prevent inkscape from starting up without crashing for you.

**Comment by lstomberg** [comment]
You can try the work around proposed in issue #51 by @weikengchen

**Comment by bytebunny** [comment]
@lstomberg, thanks! That did it.
