### ISSUE TITLE
Inkscape complains about missing LXML

### ISSUE THREAD

**Issue by yratof** [caskformula/homebrew-caskformula#5]
Inkscape extensions are having trouble locationing LXML – The thing is, LXML is installed, yet this is installed and has been reinstalled via brew / macports / pip.

Any reason why this cask doesn't include it?

**Comment by tghs** [comment]
I did a quick test for this with a barcode rendering extension (Extensions > Render > Barcode > Classic).

Without lxml installed it gives the error, as you say. But after I install `lxml` with pip (`sudo pip install lxml`), it's working as expected.

Which version of macOS are you running? I'm on 10.12.4.

Also might be worth comparing differences in Python setups:

```
· which python
/usr/local/bin/python
· ls -l /usr/local/bin/python
lrwxr-xr-x  1 tghs  admin  34 19 Dec 16:48 /usr/local/bin/python -> ../Cellar/python/2.7.13/bin/python
· env | grep PYTHON
# no output
· brew list | grep python
boost-python
python
python3
```

**Comment by yratof** [comment]
Version `10.11.6`. Experimenting around with what could have been causing this, decided to remove python via brew, perhaps at some point i'd installed it that way, but `brew uninstall --ignore-dependencies python`, then reinstalling `sudo easy_install pip` and `STATIC_DEPS=true sudo pip install lxml` got everything running on track.

I'm putting this down to perhaps conflicting python installs causing lxml to be installed not into the python that Inkscape is calling
