### ISSUE TITLE
Temporary fix

### ISSUE THREAD

**Issue by weikengchen** [caskformula/homebrew-caskformula#54]
Now, please just do the following:

```
brew cask install inkscape
```

==================================

This is a new post since #51  is too long.

There are three issues:
- the data type changes to `const char*`, which needs to update the code.
- a problem in `glibmm`, now patched in homebrew (https://github.com/Homebrew/homebrew-core/blob/master/Formula/glibmm.rb).
- `poppler` terminates the support of GooHash.

Based on the formula in this repo, I created the following:
         https://github.com/weikengchen/homebrew-caskformula
I followed the MacPorts, this formula uses Inkscape 0.92.3.

You need to:
```
brew tap weikengchen/caskformula
brew uninstall inkscape
brew install weikengchen/caskformula/inkscape
```

If you previously use `weikengchen/glibmm`, please untap my glibmm, force uninstall my glibmm, and install the one from the homebrew official. 

## Acknowledgment

Tim Sheridan (@tghs) provided the official fix for Mac.
Clemens Lang (@neverpanic) provided the fix for glibmm. @ilovezfs added that into the homebrew.
Bradley Momberger (@airhadoken) provided information about the tap and found the cause of GooHash missing.

**Comment by weikengchen** [comment]
And thanks @7Ds7 for finding out the failure of the previous formula due to the poppler upgrade.

**Comment by follower** [comment]
Worked for me for Mac OS X 10.9.5 build.

Have successfully opened/edited/saved file.

(FWIW I did need to `brew install gnutls --without-p11-kit` previously but that's not specifically related to Inkscape.)

(Also needed to `mkdir -p ~/.local/share/` to get recent files menu to work.)

Thanks all!

**Comment by vlaminck** [comment]
@weikengchen will you be opening a PR to apply your fix?

**Comment by weikengchen** [comment]
@vlaminck  I am waiting for the authors to show up...

**Comment by GrayanOne** [comment]
Just to say "Thank you" to @weikengchen, @tghs, @neverpanic, @Airhadoken. Really appreciate your work.

**Comment by intgr** [comment]
Thanks! I thought I followed these instructions properly but now I'm getting:
```
[100%] Linking CXX shared library ../lib/libinkscape_base.dylib
cd /tmp/inkscape-20180606-34874-1nw1ete/inkscape-0.92.3/build/src && /usr/local/Cellar/cmake/3.11.3/bin/cmake -E cmake_link_script CMakeFiles/inkscape_base.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ [... long list of files ...]
ld: library not found for -lgiomm-2.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libinkscape_base.dylib] Error 1
make[1]: *** [src/CMakeFiles/inkscape_base.dir/all] Error 2
make: *** [all] Error 2
```

However, I do have giomm-2.4 files:
```
/usr/local/Cellar/glibmm/2.56.0_1/include/giomm-2.4
/usr/local/Cellar/glibmm/2.56.0_1/lib/giomm-2.4
/usr/local/Cellar/glibmm/2.56.0_1/lib/pkgconfig/giomm-2.4.pc
/usr/local/Cellar/glibmm/2.56.0_1/lib/libgiomm-2.4.1.dylib
/usr/local/Cellar/glibmm/2.56.0_1/lib/libgiomm-2.4.dylib
/usr/local/Cellar/glibmm/2.56.0/include/giomm-2.4
/usr/local/Cellar/glibmm/2.56.0/lib/giomm-2.4
/usr/local/Cellar/glibmm/2.56.0/lib/pkgconfig/giomm-2.4.pc
/usr/local/Cellar/glibmm/2.56.0/lib/libgiomm-2.4.1.dylib
/usr/local/Cellar/glibmm/2.56.0/lib/libgiomm-2.4.dylib
```

Ideas?

**Comment by intgr** [comment]
I fixed my problem, Inkscape installation works after running:
```
brew switch glibmm 2.56.0_1
```

**Comment by ilovezfs** [comment]
@weikengchen I have applied the glibmm patch to the formula in Homebrew/homebrew-core in https://github.com/Homebrew/homebrew-core/pull/28801

**Comment by weikengchen** [comment]
@ilovezfs  wait! why it is closed, not merged?

**Comment by ilovezfs** [comment]
All PRs that involve new bottles show "closed" because they're merged with `brew pull --bottle` not the GitHub GUI.

**Comment by weikengchen** [comment]
so, at this moment, I think I should:

(1) not ask the users to use my formula, instead, switch to the main formula in homebrew.
          So they should untap my formula, and then, probably, force reinstall glibmm?  
(2) let the homebrew formula for inkscape requires 2.56.0_1.

Is that correct? 

I may do that during the weekend.

**Comment by ilovezfs** [comment]
Yes. You could also copy the patch blocks from https://github.com/Homebrew/homebrew-core/pull/28803 to apply the actual upstream commits instead of your custom patch file.

**Comment by dano-ai** [comment]
Thanks guys, @weikengchen @ilovezfs 

But I'm confused now. Is there a better way to install inkscape than using this temporary fix?

**Comment by weikengchen** [comment]
@dano-ai Sorry. I should update my temporary fix accordingly last month.

I will update my temporary fix now.

**Comment by ilovezfs** [comment]
```
brew cask install inkscape
```

**Comment by weikengchen** [comment]
@ilovezfs will add that to the main post.

**Comment by dano-ai** [comment]
The only difference between 2 suggestions are the version of inkscape: the former is 0.92.3 and the latter is 0.92.1.

**Comment by babahs** [comment]
just run:
`brew cask install xquartz`
`brew cask install inkscape`

> 14:43:48 iqbal@-:~$ brew cask install inkscape
> ==> Satisfying dependencies
> Error: Cask 'inkscape' requires XQuartz/X11, which can be installed using Homebrew-Cask by running
>   brew cask install xquartz
> 
> or manually, by downloading the package from
>   https://www.xquartz.org/
> 14:44:22 iqbal@-:~$ brew cask install xquartz
> ==> Satisfying dependencies
> ==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
> ######################################################################## 100.0%
> ==> Verifying checksum for Cask xquartz
> ==> Installing Cask xquartz
> ==> Running installer for xquartz; your password may be necessary.
> ==> Package installers may write to any location; options such as --appdir are ignored.
> Password:
> 
> 
> 
> installer: Package name is XQuartz 2.7.11
> installer: Installing at base path /
> installer: The install was successful.
> 🍺  xquartz was successfully installed!
> 15:03:20 iqbal@-:~$
> 15:03:20 iqbal@-:~$
> 15:03:20 iqbal@-:~$
> 15:03:20 iqbal@-:~$ brew cask install inkscape
> Updating Homebrew...
> ==> Auto-updated Homebrew!
> Updated 1 tap (homebrew/cask).
> No changes to formulae.
> 
> ==> Satisfying dependencies
> ==> Downloading https://inkscape.org/gallery/item/11269/Inkscape-0.92.2-1-x11-10.7-x86_64.dmg
> ==> Downloading from https://inkscape.org/en/gallery/item/11269/Inkscape-0.92.2-1-x11-10.7-x86_64.dmg
> ######################################################################## 100.0%
> ==> Verifying checksum for Cask inkscape
> ==> Installing Cask inkscape
> ==> Moving App 'Inkscape.app' to '/Applications/Inkscape.app'.
> ==> Linking Binary 'inkscape' to '/usr/local/bin/inkscape'.
> 🍺  inkscape was successfully installed!

**Comment by mischkl** [comment]
Hmm, Inkscape won't start on Mojave. Any suggestions?

**Comment by weikengchen** [comment]
now what you need to do is to stop using this cask and use homebrew's default.

**Comment by mischkl** [comment]
> now what you need to do is to stop using this cask and use homebrew's default.

I installed via `brew cask install inkscape`. However it installs a DMG of version 0.92.2, not 0.92.3.. not sure if that is the problem.

**Comment by weikengchen** [comment]
if you ran `brew tap` to tap this one, you need to untap.

**Comment by mischkl** [comment]
Thanks, I don't know what made the difference but untapping your tap, uninstalling and reinstalling the inkscape cask did the trick ❤️

**Comment by squidjam** [comment]
The following worked for me in Mojave:

* Install Homebrew as per instructions on the site
* `brew install caskformula/caskformula/inkscape` (fails due to ChecksumMismatchError)
* `brew edit caskformula/caskformula/inkscape` to change the failing checksum as instructed here (https://github.com/caskformula/homebrew-caskformula/issues/57#issuecomment-397919379 but fails as mentioned in link
* `brew tap weikengchen/caskformula` as instructed here https://github.com/caskformula/homebrew-caskformula/issues/54#issue-325454295
* `brew install weikengchen/caskformula/inkscape` (tries to install 0.93.x but fails due to too many errors
* `brew untap weikengchen/caskformula`
* `brew cask install xquartz` (installs successfully)
* `brew cask install inkscape` (installs 0.92.x successfully)

Maybe some of the steps can be avoided and maybe it's just that you need to run the last two....

Once installed, drag the icon to Applications, go to the folder and ***while pressing the control key*** click and select open, then give it the necessary permissions to run on your mac.

You'll have to wait... then it will open as an xQuartz app.

**Comment by ngekoding** [comment]
> The following worked for me in Mojave:
> 
> * Install Homebrew as per instructions on the site
> * `brew install caskformula/caskformula/inkscape` (fails due to ChecksumMismatchError)
> * `brew edit caskformula/caskformula/inkscape` to change the failing checksum as instructed here ([#57 (comment)](https://github.com/caskformula/homebrew-caskformula/issues/57#issuecomment-397919379) but fails as mentioned in link
> * `brew tap weikengchen/caskformula` as instructed here [#54 (comment)](https://github.com/caskformula/homebrew-caskformula/issues/54#issue-325454295)
> * `brew install weikengchen/caskformula/inkscape` (tries to install 0.93.x but fails due to too many errors
> * `brew untap weikengchen/caskformula`
> * `brew cask install xquartz` (installs successfully)
> * `brew cask install inkscape` (installs 0.92.x successfully)
> 
> Maybe some of the steps can be avoided and maybe it's just that you need to run the last two....
> 
> Once installed, drag the icon to Applications, go to the folder and _**while pressing the control key**_ click and select open, then give it the necessary permissions to run on your mac.
> 
> You'll have to wait... then it will open as an xQuartz app.

I try install with this instructions, and I get Inkscape successfully installed on my MacBook Pro 2015 Mojave. But I get something wrong when using it (see below).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11625690/49559382-3c05be80-f941-11e8-86e2-28bcfafe5b55.gif)

Any idea to solve this problem?

**Comment by weikengchen** [comment]
I think the currently recommended way, as this post suggests, is to `brew cask install inkscape` and NOT do anything else, because there is an official cask for this.

**Comment by ngekoding** [comment]
> I think the currently recommended way, as this post suggests, is to `brew cask install inkscape` and NOT do anything else, because there is an official cask for this.

Any idea to fix my problem above?

**Comment by weikengchen** [comment]
There seems to be something different today. The version I am using does not use XQuartz.

**Comment by ngekoding** [comment]
Which version that you use? Maybe I can try to install that version.

**Comment by weikengchen** [comment]
@ngekoding I tried to reproduce recently and now the version on my computer no longer works.

**Comment by trentbullard** [comment]
i'd pay for a non-xquartz mojave-native inkscape xD

**Comment by weikengchen** [comment]
Trenton, due to the circumstance, for me it is the time to switch to Adobe Illustrator.

**Comment by trentbullard** [comment]
> Trenton, due to the circumstance, for me it is the time to switch to Adobe Illustrator.

totally understandable, i meant if inkscape devs made a paid version of inkscape that was mojave-native, i'd buy it for sure.

**Comment by weikengchen** [comment]
Honestly speaking, I have been thinking to write a paper: "Free and share, burn it with fire" and point out that "free and share" has been a significant vulnerability of the Internet, and is NOT the propellant.

**Comment by weikengchen** [comment]
A little payment resolves a world of problems.
