### ISSUE TITLE
Bad SHA256 checksum

### ISSUE THREAD

**Issue by ApprenticeHuman** [caskformula/homebrew-caskformula#57]
==> Already downloaded: /Users/evdavi/Library/Caches/Homebrew/inkscape-0.92.2.tar.bz2
==> Downloading https://gitlab.com/inkscape/inkscape/commit/93ccf03162cd2e46d962
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 1f037cc29cee8e0c60ab4753d4151741c8170e4849129bac68fdc60925eb971d
Actual: 7ce4f70f1cb03cd0bab7dc94821a89bf71600bd59c763ae0d78c48f33db3d9ac
Archive: /Users/evdavi/Library/Caches/Homebrew/inkscape--patch-1f037cc29cee8e0c60ab4753d4151741c8170e4849129bac68fdc60925eb971d.diff

I did remove the file and tried downloading, several times. The SHA256 checksums stay the same and are mismatched.

Update 20180614:
No response after 6 days: all that is needed is to rename the file to inkscape--patch-7ce4f70f1cb03cd0bab7dc94821a89bf71600bd59c763ae0d78c48f33db3d9ac and republish the manifest. So it's not a big ask, is it?

**Comment by mkleinschnitker** [comment]
Same problem for me.

**Comment by npanousis** [comment]
Same problem for me too

**Comment by onc4hy** [comment]
Same problem for me too,retry and again

**Comment by swalkerllan** [comment]
Me too!

**Comment by peterwake** [comment]
Me too

**Comment by herlanijunior** [comment]
up !

**Comment by CThuleHansen** [comment]
Bump

**Comment by desiringm** [comment]
...

**Comment by yogeeko** [comment]
up!

**Comment by sparr** [comment]
`brew edit caskformula/caskformula/inkscape`

replace `1f037cc29cee8e0c60ab4753d4151741c8170e4849129bac68fdc60925eb971d` with `7ce4f70f1cb03cd0bab7dc94821a89bf71600bd59c763ae0d78c48f33db3d9ac`

**Comment by peterwake** [comment]
@sparr that fixed this issue for me (did that then tried running `brew install caskformula/caskformula/inkscape` again), but now I'm getting the goo/GooHash.h bug reported in https://github.com/caskformula/homebrew-caskformula/issues/55!

**Comment by ApprenticeHuman** [comment]
@sparr Thanks, that got me to the goo/GooHash.h bug.

This still failed but led tme to [Issue 54](https://github.com/caskformula/homebrew-caskformula/issues/54) which has the 4 steps needed to install inkscape 0.92.3!

+1 to weikengchen

It's not a great solution as it involves using Chen's tap/fork of the formula but it'll do until someone fixes the main line.
