### ISSUE TITLE
can't link intltool

### ISSUE THREAD

**Issue by cramhead** [caskformula/homebrew-caskformula#7]
When I attempt to install the install says that it can't proceed with linking the intltool. When I attempt to do so it fails
$ brew link intltool
Linking /usr/local/Cellar/intltool/0.51.0...
Error: Could not symlink share/man/man8/intltool-extract.8
/usr/local/share/man/man8 is not writable.

**Comment by tghs** [comment]
Sorry for the delay, can you share the output of `ls -l /usr/local/share/man`?

**Comment by cramhead** [comment]
Thanks

**Comment by tghs** [comment]
For reference, more discussion of this issue is in #10.
