### ISSUE TITLE
inkscape - How to set the language?

### ISSUE THREAD

**Issue by beamholder** [caskformula/homebrew-caskformula#8]
Hello. Following the Homebrew install instructions at:
    https://inkscape.org/en/download/mac-os/
using:
    brew install caskformula/caskformula/inkscape
did install, however launching inkscape from the Xquartz bash window by typing:
  inkscape
does launch the program but the  GUI is in what looks like Portuguese. How do I launch it in English?

**Comment by denmaus** [comment]
set your locale and start the program with `LANG=en_US inkscape`
