### ISSUE TITLE
brew update error

### ISSUE THREAD

**Issue by renate73** [caskformula/homebrew-caskformula#82]
Error: Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the caskformula/caskformula tap:
  /usr/local/Homebrew/Library/Taps/caskformula/homebrew-caskformula/Formula/inkscape.rb:49

**Comment by paulocastellano** [comment]
+1

**Comment by der-test** [comment]
👍

**Comment by richardwonka** [comment]
How man +1s would you like?

**Comment by jamesb93** [comment]
+1
