### ISSUE TITLE
installation failed on glibmm

### ISSUE THREAD

**Issue by supergglue** [caskformula/homebrew-caskformula#9]
I'm not an expert, so I will not try fancy things, but after typing 
brew install caskformula/caskformula/inkscape

I got after a few successful installations:
==> Downloading https://homebrew.bintray.com/bottles/glibmm-2.50.1.sierra.bottle.tar.gz

curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "glibmm"
Download failed: https://homebrew.bintray.com/bottles/glibmm-2.50.1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://download.gnome.org/sources/glibmm/2.50/glibmm-2.50.1.tar.xz

curl: (6) Could not resolve host: download.gnome.org
Error: Failed to download resource "glibmm"
Download failed: https://download.gnome.org/sources/glibmm/2.50/glibmm-2.50.1.tar.xz

so ... I don't know

**Comment by tghs** [comment]
These URLs are resolving fine for me trying them just now. Can you try again in case it was a temporary problem with GNOME's download service?
