### ISSUE TITLE
"cxx11" is not a recognized standard

### ISSUE THREAD

**Issue by kyle-sung** [caskformula/homebrew-caskformula#90]
Tried installing inkscape using the caskformula into homebew and this happened:
--------------------------------
==> Tapping caskformula/caskformula
Cloning into '/usr/local/Homebrew/Library/Taps/caskformula/homebrew-caskformula'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskformula/homebrew-caskformula/Formula/inkscape.rb
inkscape: "cxx11" is not a recognized standard
Error: Cannot tap caskformula/caskformula: invalid syntax in tap!

**Comment by korpharos** [comment]
Try 
`brew cask install inkscape`
it just worked for me.

**Comment by t1mwillis** [comment]
You may have to run `brew cask install xquartz` before as well.

After that, restart your machine.

**Comment by jcolomb** [comment]
To upgrade, I had to do several things, I think those commands are the one who worked (I did not had to restart):


brew cask reinstall xquartz
brew cask uninstall inkscape
brew cleanup
brew cask install inkscape

**Comment by morrison1977** [comment]
Well I get:
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskformula/homebrew-caskformula/Formula/inkscape.rb
inkscape: "cxx11" is not a recognized standard
Error: Cannot tap caskformula/caskformula: invalid syntax in tap!

Then after reinstalling it still does not open, the icon pops up then goes away...gone

➜  ~ brew cask reinstall xquartz
==> Satisfying dependencies
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
Already downloaded: /Users/bmorrison/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Verifying SHA-256 checksum for Cask 'xquartz'.
==> Uninstalling Cask xquartz
==> Removing launchctl service org.macosforge.xquartz.startx
==> Removing launchctl service org.macosforge.xquartz.privileged_startx
==> Uninstalling packages:
org.macosforge.xquartz.pkg
==> Removing files:
/opt/X11
/private/etc/manpaths.d/40-XQuartz
/private/etc/paths.d/40-XQuartz
==> Purging files for version 2.7.11 of Cask xquartz
==> Installing Cask xquartz
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is XQuartz 2.7.11
installer: Installing at base path /
installer: The install was successful.
🍺  xquartz was successfully installed!
➜  ~ brew cask reinstall inkscape
==> Satisfying dependencies
==> Downloading https://media.inkscape.org/dl/resources/file/Inkscape-0.92.2-1-x11-10.7-x86_64.dmg
Already downloaded: /Users/bmorrison/Library/Caches/Homebrew/downloads/fe3384b679b6affc100346326133835dfac32945f64918385b1803e985821348--Inkscape-0.92.2-1-x11-10.7-x86_64.dmg
==> Verifying SHA-256 checksum for Cask 'inkscape'.
==> Uninstalling Cask inkscape
==> Backing App 'Inkscape.app' up to '/usr/local/Caskroom/inkscape/0.92.2-1/Inkscape.app'.
==> Removing App '/Applications/Inkscape.app'.
==> Unlinking Binary '/usr/local/bin/inkscape'.
==> Purging files for version 0.92.2-1 of Cask inkscape
==> Installing Cask inkscape
==> Moving App 'Inkscape.app' to '/Applications/Inkscape.app'.
==> Linking Binary 'inkscape' to '/usr/local/bin/inkscape'.
🍺  inkscape was successfully installed!

**Comment by ankush981** [comment]
I didn't have to restart. I followed @jcolomb's instructions and it all went smoothly!

**Comment by roadking** [comment]
I followed @jcolomb 's instructions also with immediate success.
Thank you Julien!

**Comment by CriticalUpdate** [comment]
> You may have to run `brew cask install xquartz` before as well.
> 
> After that, restart your machine.

I thought I had installed xquartz already, but I apparently did it wrong as I kept getting errors. Over a year later and I finally have Inkscpae on my Mac, thank you.

**Comment by DanielRuf** [comment]
For me it did not work with xquartz. Is there something that we have to add to / do with the PATH variable?

**Comment by DanielRuf** [comment]
```
brew install caskformula/caskformula/inkscape
Updating Homebrew...
==> Tapping caskformula/caskformula
Cloning into '/usr/local/Homebrew/Library/Taps/caskformula/homebrew-caskformula'...
remote: Enumerating objects: 78, done.
remote: Total 78 (delta 0), reused 0 (delta 0), pack-reused 78
Receiving objects: 100% (78/78), 8.96 KiB | 1.28 MiB/s, done.
Resolving deltas: 100% (18/18), done.
Warning: Calling BuildOptions#include? is deprecated! There is no replacement.
Please report this issue to the caskformula/caskformula tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/caskformula/homebrew-caskformula/Formula/inkscape.rb:11

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskformula/homebrew-caskformula/Formula/inkscape.rb
inkscape: "cxx11" is not a recognized standard
Error: Cannot tap caskformula/caskformula: invalid syntax in tap!
```

**Comment by DanielRuf** [comment]
It seems the homebrew version is not recommended anymore and there is only the dmg file linked at https://inkscape.org/de/release/inkscape-1.0.1/mac-os-x/ for Inkscape 1.x.

**Comment by kolohelios** [comment]
`brew install inkscape` just worked for me on OS X 11.4 Big Sur and installed 1.1.0. It looks like it's just grabbing an app package and not building from scratch.
